---
- name: Ensure GPG is installed
  become: true
  ansible.builtin.apt:
    name: gpg-agent
    state: present

- name: Import Jellyfin GPG key
  become: true
  ansible.builtin.apt_key:
    url: https://repo.jellyfin.org/debian/jellyfin_team.gpg.key
    state: present

- name: Add Jellyfin repository
  become: true
  ansible.builtin.file:
    path: /etc/apt/sources.list.d/jellyfin.sources
    content: |
      Types: deb
      URIs: https://repo.jellyfin.org/{{ ansible_distribution | lower }}
      Suites: {{ ansible_distribution_release }}
      Components: main
      Architectures: {{ jellyfin_install_arch_mapping[ansible_architecture] }}


- name: Install Jellyfin
  become: true
  ansible.builtin.apt:
    name:
      - jellyfin
      - jellyfin-ffmpeg5
    state: present

- name: Ensure video and render group exist
  ansible.builtin.group:
    name: "{{ item }}"
    state: present
  loop:
    - video
    - render
- name: Add Jellyfin user to video and render group
  become: true
  ansible.builtin.user:
    name: jellyfin
    groups:
      - video
      - render
    append: true

...
