---
dependency:
  name: galaxy
driver:
  name: podman
platforms:
  - name: debian11
    image: docker.io/geerlingguy/docker-debian11-ansible
    pre_build_image: true
    systemd: true
    tmpfs:
      "/tmp": "rw,exec,mode=1777"
      "/run": "rw,noexec,nosuid,nodev"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    cgroupns_mode: host
    privileged: true
    command: "/sbin/init"
provisioner:
  name: ansible
  env:
    ANSIBLE_LOCAL_TEMP: "${HOME}/.ansible/tmp"
    ANSIBLE_REMOTE_TMP: /tmp/ansible
verifier:
  name: ansible

...
