---
dependency:
  name: galaxy
driver:
  name: podman
platforms:
  - name: debian11
    image: docker.io/geerlingguy/docker-debian11-ansible
    pre_build_image: true
    systemd: true
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    command: "/sbin/init"
provisioner:
  name: ansible
  env:
    ANSIBLE_LOCAL_TEMP: "${HOME}/.ansible/tmp"
    ANSIBLE_REMOTE_TMP: /tmp/ansible
verifier:
  name: ansible

...
